# Generated by Django 6.1.1 on 2026-09-07 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnershipClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted — Proceed to Return'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('answer_text', models.TextField(help_text="Claimant's description of private identifying details")),
                ('proof_image', models.ImageField(blank=True, help_text='Purchase receipt, old photo, ID snippet, etc.', null=True, upload_to='claim_proofs/')),
                ('additional_info', models.TextField(blank=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('handover_otp', models.CharField(blank=True, max_length=6)),
                ('is_handover_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_claims', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='matching.match')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('match', 'claimant')},
            },
        ),
        migrations.CreateModel(
            name='ReturnConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finder_confirmed', models.BooleanField(default=False)),
                ('owner_confirmed', models.BooleanField(default=False)),
                ('finder_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='return_confirmation', to='claims.ownershipclaim')),
            ],
        ),
    ]
