# Generated by Django 6.1.1 on 2026-09-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipclaim',
            name='ai_confidence',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='ownershipclaim',
            name='ai_reasoning',
            field=models.TextField(blank=True, help_text='AI reasoning summary'),
        ),
        migrations.AddField(
            model_name='ownershipclaim',
            name='ai_score',
            field=models.FloatField(blank=True, help_text='AI match score 0-100', null=True),
        ),
        migrations.AddField(
            model_name='ownershipclaim',
            name='is_ai_verified',
            field=models.BooleanField(default=False),
        ),
    ]
