# Generated by Django 6.1.1 on 2026-09-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_ownershipclaim_ai_confidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipclaim',
            name='interview_history',
            field=models.JSONField(blank=True, default=list, help_text='Interactive AI chat interview history'),
        ),
        migrations.AlterField(
            model_name='ownershipclaim',
            name='answer_text',
            field=models.TextField(blank=True, default='', help_text="Claimant's description of private identifying details"),
        ),
        migrations.AlterField(
            model_name='ownershipclaim',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'AI Verification in Progress'), ('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted — Proceed to Return'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
