# Generated by Django 6.1.1 on 2026-09-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_ownershipclaim_interview_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownershipclaim',
            name='finder_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownershipclaim',
            name='finder_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ownershipclaim',
            name='handover_otp',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
