# Generated by Django 6.1.1 on 2026-09-08 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='ai_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='is_ai_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='conversation',
            name='status',
            field=models.CharField(choices=[('AI_VERIFICATION', 'AI Verification'), ('PENDING_FINDER', 'AI Verified — Awaiting Finder'), ('ACTIVE', 'Active Handover Chat'), ('CLOSED', 'Closed — Item Returned')], default='ACTIVE', max_length=25),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_proofs/'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_ai',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='TEXT', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
