# Generated by Django 6.1.1 on 2026-09-07 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('icon', models.CharField(default='📦', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('LOST', 'Lost — I lost this item'), ('FOUND', 'Found — I found this item')], max_length=10)),
                ('title', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(blank=True, help_text='e.g. Black, Silver, Navy Blue', max_length=80)),
                ('description', models.TextField(help_text='Public description — do NOT include secret identifying details.')),
                ('location_name', models.CharField(blank=True, help_text='Landmark, station, etc.', max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_event', models.DateField(help_text='Date when item was lost or found')),
                ('time_event', models.TimeField(blank=True, help_text='Approximate time (optional)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_photos/')),
                ('embedding_json', models.TextField(blank=True, help_text='Internal: serialized text embedding vector')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATCH_FOUND', 'Match Found'), ('CLAIM_PENDING', 'Claim Pending'), ('VERIFIED', 'Ownership Verified'), ('RETURNED', 'Returned'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='items.category')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_photos/extra/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_images', to='items.item')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden_info', models.TextField(help_text='Unique marks, contents, scratches, stickers, etc.')),
                ('challenge_question', models.CharField(blank=True, default='Describe the unique private marks or contents of the item.', max_length=255)),
                ('serial_hint', models.CharField(blank=True, help_text='Last 4 digits of serial / IMEI — optional', max_length=100)),
                ('additional_notes', models.TextField(blank=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='private_detail', to='items.item')),
            ],
        ),
    ]
