# Generated by Django 6.1.1 on 2026-09-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_score', models.FloatField(default=0.0)),
                ('text_score', models.FloatField(default=0.0)),
                ('category_score', models.FloatField(default=0.0)),
                ('color_score', models.FloatField(default=0.0)),
                ('location_score', models.FloatField(default=0.0)),
                ('date_score', models.FloatField(default=0.0)),
                ('final_score', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('DETECTED', 'Detected'), ('NOTIFIED', 'User Notified'), ('CLAIMED', 'Claim Submitted'), ('UNDER_REVIEW', 'Under Verification'), ('ACCEPTED', 'Claim Accepted'), ('REJECTED', 'Claim Rejected'), ('RETURNED', 'Item Returned')], default='DETECTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('found_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_found', to='items.item')),
                ('lost_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_lost', to='items.item')),
            ],
            options={
                'ordering': ['-final_score'],
                'unique_together': {('lost_item', 'found_item')},
            },
        ),
    ]
